# Dependabot configuration for MacForge
# Simplified configuration to reduce failures

version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/DesktopApp"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "Aussie-Nomad"
    assignees:
      - "Aussie-Nomad"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "swift"
