name: Build and Test MacForge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
    
    - name: Build project
      working-directory: DesktopApp
      run: |
        echo "Building MacForge project..."
        if [ -f "MacForge.xcodeproj/project.pbxproj" ]; then
          xcodebuild -project MacForge.xcodeproj -scheme MacForge -destination 'platform=macOS,arch=x86_64' build
          echo "Build completed successfully!"
        elif [ -f "MacForge.xcworkspace/contents.xcworkspacedata" ]; then
          xcodebuild -workspace MacForge.xcworkspace -scheme MacForge -destination 'platform=macOS,arch=x86_64' build
          echo "Build completed successfully!"
        else
          echo "No Xcode project or workspace found in DesktopApp directory"
          ls -la
          exit 1
        fi
    
    - name: Run tests (if available)
      working-directory: DesktopApp
      run: |
        echo "Running tests..."
        if [ -f "MacForge.xcodeproj/project.pbxproj" ]; then
          xcodebuild -project MacForge.xcodeproj -scheme MacForge -destination 'platform=macOS,arch=x86_64' test
          echo "Tests completed successfully!"
        elif [ -f "MacForge.xcworkspace/contents.xcworkspacedata" ]; then
          xcodebuild -workspace MacForge.xcworkspace -scheme MacForge -destination 'platform=macOS,arch=x86_64' test
          echo "Tests completed successfully!"
        else
          echo "No tests to run"
        fi
      continue-on-error: true
