name: Build and Test MacForge
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build project
      working-directory: DesktopApp
      run: |
        xcodebuild -project MacForge.xcodeproj -scheme MacForge -destination 'platform=macOS' build
    
    - name: Run tests
      working-directory: DesktopApp
      run: |
        xcodebuild -project MacForge.xcodeproj -scheme MacForge -destination 'platform=macOS' test
      continue-on-error: true
