name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get tag name
      id: get_tag
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        VERSION=${TAG#v}
        echo "TAG=$TAG" >> $GITHUB_OUTPUT
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Tag: $TAG, Version: $VERSION"

    - name: Set up Xcode
      run: |
        # Use the default Xcode version
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version

    - name: Build Release App
      run: |
        cd DesktopApp
        echo "Building MacForge Release v${{ steps.get_tag.outputs.VERSION }}..."
        
        # Clean first
        xcodebuild clean -project MacForge.xcodeproj -scheme MacForge -configuration Release
        
        # Build
        xcodebuild build \
          -project MacForge.xcodeproj \
          -scheme MacForge \
          -configuration Release \
          -destination 'platform=macOS' \
          -derivedDataPath ./build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          MARKETING_VERSION="${{ steps.get_tag.outputs.VERSION }}" \
          CURRENT_PROJECT_VERSION=1
              
    - name: Create Release Archive
      run: |
        TAG_NAME="${{ steps.get_tag.outputs.TAG }}"
        VERSION="${{ steps.get_tag.outputs.VERSION }}"
        APP_NAME="MacForge"
        RELEASE_APP_PATH="DesktopApp/build/Build/Products/Release/${APP_NAME}.app"
        DIST_DIR="dist"
        
        echo "Creating release archive for $TAG_NAME (version $VERSION)"
        
        # Check if app exists
        if [ ! -d "$RELEASE_APP_PATH" ]; then
          echo "❌ Error: Application not found at $RELEASE_APP_PATH"
          echo "Available files in build directory:"
          find DesktopApp/build -name "*.app" -type d 2>/dev/null || echo "No .app files found"
          exit 1
        fi
        
        mkdir -p "$DIST_DIR"
        cp -R "$RELEASE_APP_PATH" "$DIST_DIR/${APP_NAME}-${TAG_NAME}.app"
        
        cd "$DIST_DIR"
        zip -r "${APP_NAME}-${TAG_NAME}.zip" "${APP_NAME}-${TAG_NAME}.app"
        shasum -a 256 "${APP_NAME}-${TAG_NAME}.zip" > "${APP_NAME}-${TAG_NAME}.zip.sha256"
        
        echo "RELEASE_ZIP_PATH=${DIST_DIR}/${APP_NAME}-${TAG_NAME}.zip" >> $GITHUB_ENV
        echo "RELEASE_CHECKSUM_PATH=${DIST_DIR}/${APP_NAME}-${TAG_NAME}.zip.sha256" >> $GITHUB_ENV
        
        echo "✅ Release files created:"
        ls -la

    - name: Read Release Notes
      id: read_release_notes
      run: |
        if [ -f "RELEASE_NOTES.md" ]; then
          RELEASE_NOTES=$(cat RELEASE_NOTES.md)
        else
          RELEASE_NOTES="## MacForge ${{ steps.get_tag.outputs.TAG }}

### What's New
- DDM Blueprints Tool - Complete Device Data Management Blueprint System
- Enhanced security and GDPR compliance features
- Improved user interface and accessibility
- Bug fixes and performance improvements

### Installation
1. Download the \`MacForge-${{ steps.get_tag.outputs.TAG }}.zip\` file
2. Unzip the archive
3. Drag \`MacForge.app\` to your Applications folder
4. Launch MacForge

### System Requirements
- macOS 15.5 (Sonoma) or later
- 100 MB available disk space"
        fi
        
        # Escape newlines and double quotes for JSON
        RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
        RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
        RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
        echo "release_body=$RELEASE_NOTES" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_tag.outputs.TAG }}
        name: MacForge ${{ steps.get_tag.outputs.TAG }}
        body: ${{ steps.read_release_notes.outputs.release_body }}
        draft: false
        prerelease: false
        files: |
          ${{ env.RELEASE_ZIP_PATH }}
          ${{ env.RELEASE_CHECKSUM_PATH }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
